[project]
name = "praxis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kiskaadee", email = "fcortesbio@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.54",
    "sqlmodel>=0.0.47",
]

[project.scripts]
praxis = "praxis:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
